### ISSUE TITLE
Dúvida sobre o backend

### ISSUE THREAD

**Issue by GSFranzoni** [UNIFAGOC/ProcessoSeletivo#2]
Pode ser usado algum framework no backend?

**Comment by carlosbarretoeng** [comment]
Olá @GSFranzoni !

Muito obrigado pela questão!

Toda informação que você precisa para realizar a avaliação esta na descrição. A utilização de qualquer framework é permitida, mas avaliaremos seu entendimento sobre o funcionamento do mesmo e sua implementação dos itens solicitados. Então, sinta-se livre pra expor o máximo que conseguir!

Att.,

Carlos Barreto
Supervisor de Desenvolvimento
